# NumPy Sorting Arrays

# Sorting Arrays

In [1]:
# Sort the array:

import numpy as np

arr = np.array([3, 2, 0, 1])

print(np.sort(arr)) 

[0 1 2 3]


In [2]:
# Sort the array alphabetically:

import numpy as np

arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr)) 

['apple' 'banana' 'cherry']


In [3]:
# Sort a boolean array:

import numpy as np

arr = np.array([True, False, True])

print(np.sort(arr)) 

[False  True  True]


# Sorting a 2-D Array

In [4]:
# Sort a 2-D array:

import numpy as np

arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr)) 

[[2 3 4]
 [0 1 5]]


In [5]:
# Use the correct NumPy method to return a sorted array.

arr = np.array([3, 2, 0, 1])

x = np.sort(arr)

x

array([0, 1, 2, 3])