# NumPy Creating Arrays

# Create a NumPy ndarray Object

In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [2]:
# Use a tuple to create a NumPy array:

import numpy as np

arr = np.array((1, 2, 3, 4, 5))

print(arr) 

[1 2 3 4 5]


# Dimensions in Arrays

# 0-D Arrays

In [3]:
# Create a 0-D array with value 42

import numpy as np

arr = np.array(42)

print(arr) 

42


# 1-D Arrays

In [4]:
# Create a 1-D array containing the values 1,2,3,4,5:

import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr) 

[1 2 3 4 5]


# 2-D Arrays

In [5]:
# Create a 2-D array containing two arrays with the values 1,2,3 and 4,5,6:

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr) 

[[1 2 3]
 [4 5 6]]


# 3-D arrays

In [6]:
# Create a 3-D array with two 2-D arrays, both containing two arrays with the values 1,2,3 and 4,5,6:

import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr) 

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


# Check Number of Dimensions?

In [7]:
# Check how many dimensions the arrays have:

import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim) 

0
1
2
3


# Higher Dimensional Arrays

In [8]:
# Create an array with 5 dimensions and verify that it has 5 dimensions:

import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim) 

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [9]:
# Insert the correct method for creating a NumPy array.

arr = np.array([1, 2, 3, 4, 5])

arr

array([1, 2, 3, 4, 5])