# Data Types in Python

# Data Types in NumPy

# Checking the Data Type of an Array

In [1]:
# Get the data type of an array object:

import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr.dtype) 

int32


In [2]:
# Get the data type of an array containing strings:

import numpy as np

arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype) 

<U6


# Creating Arrays With a Defined Data Type

In [3]:
# Create an array with data type string:

import numpy as np

arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype) 

[b'1' b'2' b'3' b'4']
|S1


In [4]:
# Create an array with data type 4 bytes integer:

import numpy as np

arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype) 

[1 2 3 4]
int32


# What if a Value Can Not Be Converted?

In [5]:
# A non integer string like 'a' can not be converted to integer (will raise an error):

import numpy as np

arr = np.array(['a', '2', '3'], dtype='i') 

ValueError: invalid literal for int() with base 10: 'a'

# Converting Data Type on Existing Arrays

In [6]:
# Change data type from float to integer by using 'i' as parameter value:

import numpy as np

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype) 

[1 2 3]
int32


In [7]:
# Change data type from float to integer by using int as parameter value:

import numpy as np

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype(int)

print(newarr)
print(newarr.dtype) 

[1 2 3]
int32


In [9]:
# Change data type from integer to boolean:

import numpy as np

arr = np.array([1, 0, 3])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype) 

[ True False  True]
bool


In [10]:
# Insert the correct NumPy syntax to print the data type of an array.

arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int32


In [11]:
# Insert the correct argument to specify that the array should be of type STRING.

arr = np.array([1, 2, 3, 4], dtype='S' )

In [12]:
# Insert the correct method to change the data type to integer.


arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')