# NumPy Array Copy vs View

# The Difference Between Copy and View

# COPY:

In [1]:
# Make a copy, change the original array, and display both arrays:

import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x) 

[42  2  3  4  5]
[1 2 3 4 5]


# VIEW:

In [2]:
# Make a view, change the original array, and display both arrays:

import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x) 

[42  2  3  4  5]
[42  2  3  4  5]


# Make Changes in the VIEW:

In [3]:
# Make a view, change the view, and display both arrays:

import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 31

print(arr)
print(x) 

[31  2  3  4  5]
[31  2  3  4  5]


# Check if Array Owns its Data

In [4]:
# Print the value of the base attribute to check if an array owns it's data or not:

import numpy as np

arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base) 

None
[1 2 3 4 5]


In [5]:
# Use the correct method to make a copy of the array.

arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()

print(x)

[1 2 3 4 5]


In [6]:
# Use the correct method to make a view of the array.


arr = np.array([1, 2, 3, 4, 5])

x = arr.view()

print(x)

[1 2 3 4 5]
