# NumPy Array Shape

# Shape of an Array

# Get the Shape of an Array

In [1]:
# Print the shape of a 2-D array:

import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape) 

(2, 4)


In [2]:
# Create an array with 5 dimensions using ndmin using a vector with values 1,2,3,4 and verify that last dimension has value 4:

import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape) 

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


# What does the shape tuple represent?

In [3]:
# Use the correct NumPy syntax to check the shape of an array.


arr = np.array([1, 2, 3, 4, 5])

print(arr.shape)


(5,)


In [4]:
# Use the correct NumPy method to change the shape of an array from 1-D to 2-D.


arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

newarr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [5]:
# Use a correct NumPy method to change the shape of an array from 2-D to 1-D.


arr = np.array([[1, 2, 3, 4, 5, 6], [7, 8, 9, 10, 11, 12]])

newarr = arr.reshape(-1)

newarr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])